export const data = [
  {
    id: 1,
    title: "日 (nichi, jitsu)",
    kanji: "日",
    onyomi: "ニチ, ジツ",
    onromaji: "nichi, jitsu",
    kunyomi: "ひ, -び, -か",
    kunromaji: "hi, -bi, -ka",
    meaning: "Day, sun, Japan, counter for days",
    jlpt: "N5",
  },
  {
    id: 2,
    title: "一 (ichi)",
    kanji: "一",
    onyomi: "イチ",
    onromaji: "ichi",
    kunyomi: "ひと(つ)",
    kunromaji: "hito(tsu)",
    meaning: "One",
    jlpt: "N5",
  },
  {
    id: 3,
    title: "国 (koku)",
    kanji: "国",
    onyomi: "コク",
    onromaji: "koku",
    kunyomi: "くに",
    kunromaji: "kuni",
    meaning: "Country",
    jlpt: "N5",
  },
]
